# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeros', '0005_auto_20171110_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palazzo',
            old_name='num_items',
            new_name='num_of_items',
        ),
        migrations.AlterField(
            model_name='palazzo',
            name='color',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Black', 'Black'), ('Green', 'Green'), ('Blue', 'Blue')], default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='palazzo',
            name='sp',
            field=models.IntegerField(default=399),
        ),
    ]
