# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.SlugField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('brand', models.CharField(default='Emeros', max_length=6)),
                ('mrp', models.IntegerField()),
                ('selling_price', models.FloatField()),
                ('keyword', models.TextField()),
                ('country', models.CharField(default='India', max_length=5)),
            ],
        ),
    ]
